name: Test/Coverage with Python

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        id: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install needed debian packages
        run: sudo apt install libsodium-dev libgmp-dev

      - name: Install project
        run: pip install -e .

      - name: Install pytest and pytest-cov
        run: pip install pytest pytest-cov

      - name: Run tests
        run: pytest --cov-branch --cov-report=xml
        
      - name: Upload coverage reports to Codecov                                                                                                                                     
        uses: codecov/codecov-action@v5.4.0                                                                                                                                          
        with:                                                                                                                                                                        
          token: ${{ secrets.CODECOV_TOKEN }}                                                                                                                                        
          slug: aleph-im/pytezos-crypto
